name: Check Commit Messages
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  check-commit-messages:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Check for WIP
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(?!WIP)'
          flags: 'gmi'
          error: Work in progress
          checkAllCommitMessages: true
          accessToken: ${{ secrets.GITHUB_TOKEN }}
